### PR TITLE
patchelf.cc: handle DT_MIPS_XHASH and .MIPS.xhash

### LINKED ISSUE #368: Inconsistency detected by ld.so: dl-lookup.c: 966: _dl_setup_hash: Assertion `(bitmask_nwords & (bitmask_nwords - 1)) == 0' failed!
**Describe the bug**

During the nixpkgs bootstrap process, binaries which link against a patchelf'ed `librt.so.1` abort with:

```
Inconsistency detected by ld.so: dl-lookup.c: 966: _dl_setup_hash: Assertion `(bitmask_nwords & (bitmask_nwords - 1)) == 0' failed! #368 
```

**Steps To Reproduce**

1. Set your `NIX_PATH` explicitly, if you have not yet done so (i.e. such that `$NIX_PATH/nixpkgs/` points to a git checkout of nixpkgs).

2. Execute these commands to build the mips64el bootstrap tools, mips64el-nix, and launch a mips64el qemu VM:

```bash
# Assumes you have set $NIX_PATH explicitly.  If not, do so.

cd $NIX_PATH/nixpkgs

git fetch https://github.com/a-m-joseph/nixpkgs patchelf-issue-368
git switch -c patchelf-issue-368 FETCH_HEAD

cd /tmp  # or elsewhere
git clone -b patchelf-issue https://github.com/a-m-joseph/mips64-nixpkgs-qemu
cd mips64-nixpkgs-qemu
nix-shell shell.nix --argstr NIXPATH $NIX_PATH
```

Once the VM boots to a root shell, paste this command:

```
./demo.sh
```

You should get:

```
Inconsistency detected by ld.so: dl-lookup.c: 966: _dl_setup_hash: Assertion `(bitmask_nwords & (bitmask_nwords - 1)) == 0' failed!
error: builder for '/nix/store/76h8qjiv0kr99n87g01qz3sq4z5svikv-bootstrap-tools.drv' failed with exit code 127
```

This is due to the attempt to `patchelf --set-rpath librt.so`; if you don't patchelf that, (but instead patchelf other libraries, as I do [here](https://github.com/NixOS/nixpkgs/pull/161925)), you won't get this error.  Note that `librt.so` has no RPATH prior to patchelf'ing.  I suspect that the problem here is some corner case involving `--set-rpath` on a library that did not have one to begin with.

**Expected behavior**

The bootstrap completes.

**`patchelf --version` output**

```
# LD_LIBRARY_PATH=lib lib/ld.so.1 ./patchelf  --version
patchelf 0.14.5
```

**Additional context**

The [last commit](https://github.com/a-m-joseph/nixpkgs/commit/b487fba369092e5328f04dfc2dfa47ffff0e2916) in the nixpkgs repo used above is just a bit of paranoia; you can drop that commit and you'll still get the same result.

I discussed this bug [here](https://github.com/NixOS/patchelf/issues/250#issuecomment-1051603936) but I'm no longer sure it is the same problem the person who opened that bug was having.  In order to avoid hijacking their bug I am opening a separate one now that I have a simple way to reproduce the issue.

### PR DESCRIPTION
**Pull request by amjoseph-nixpkgs**
glibc changed their ABI in commit [23c1c256ae7b0f010d0fcaff60682b620887b164](https://sourceware.org/git/?p=glibc.git;a=commit;h=23c1c256ae7b0f010d0fcaff60682b620887b164) on 2019-Aug-29, by changing the structure of the `.gnu.hash` data on MIPS and moving it to a different section.  We need to adapt to this change by glibc.

Closes #368

### CODE REVIEW

**Comment by a-m-joseph** [comment]
This fixes #368 on my testing setup.

Will reverify once I confirm that it fixes the QEMU-VM test case in that PR, but I'm pretty darn sure it will work.

File: src/patchelf.cc [hunk 1]
```diff
@@ -990,6 +990,10 @@ void ElfFile<ElfFileParamNames>::rewriteHeaders(Elf_Addr phdrAddress)
                 // some binaries might this section stripped
                 // in which case we just ignore the value.
                 if (shdr) dyn->d_un.d_ptr = (*shdr).get().sh_addr;
+	    } else if (d_tag == DT_MIPS_XHASH) {
```
Comment (Mic92) [inline src/patchelf.cc:993]: nitpick: indent is a bit off here.

**Review by klemensn — APPROVED** [review]

**Comment by a-m-joseph** [comment]
This bug has been sufficiently frustrating to track down that I want to make sure I've completely documented how to both (a) reproduce it and (b) verify that it is fixed.  I'm currently running the commands below (which require quite a lot of rebuilding); as soon as they finish sometime tonight I will undraftify this PR.  Thank you for your patience.

Instructions for verifying this bug, and the fact that it is indeed fixed (based on https://github.com/NixOS/patchelf/issues/368):

```
# Assumes you have set $NIX_PATH explicitly.  If not, do so.
cd $NIX_PATH/nixpkgs
git fetch https://github.com/a-m-joseph/nixpkgs patchelf-issue-368 # e642d58dd59d40d8b2062b5ac33d053aab37cfc6
git switch -c patchelf-issue-368 FETCH_HEAD

cd /tmp  # or elsewhere
git clone -b patchelf-issue https://github.com/a-m-joseph/mips64-nixpkgs-qemu # 69126a995bc8b6a2f33b80fd5cb456acdf8a6a07
cd mips64-nixpkgs-qemu
nix-shell shell.nix --argstr NIXPATH $NIX_PATH
```

Once the VM boots, type `./demo.sh` and you should get a crash with `Inconsistency detected by ld.so ... (bitmask_nwords & (bitmask_nwords - 1)) == 0 failed`.

Then, shut down the VM, cherry-pick https://github.com/NixOS/nixpkgs/pull/178207/commits/12618e79868f81165f3fb5ae614183b715849ab6 into your `$NIX_PATH/nixpkgs` and run the `nix-shell` command above again; the bootstrap-tools should unpack correctly with no crash.

**Comment by a-m-joseph** [comment]
Yep, it works, and the steps above reproduce the problem and verify the fix.

**Comment by klemensn** [comment]
> Yep, it works, and the steps above reproduce the problem and verify the fix.

I have not reproduced your issue due to limited resources but the fix makes sense.

**Comment by amjoseph-nixpkgs** [comment]
Ping...
